### ISSUE TITLE
Type Conversion Functions

### ISSUE THREAD

**Issue by julianGoh17** [julianGoh17/simple-e2e#10]
Since `<stage>.step[].variables` can only be converted to a String and users will then need to manually cast by themselves. This should be handled by the framework by being able to pass in the string and the conversion will be handled for them:

```
      - description: "Create mock API endpoint"
        variables:
          URL: "localhost:8080/v1/weather"
          RETRIES: "1"
```

For example we should be able to call:
```
converter.GetInteger(ts, "NUM_COUNT")
```
